### ISSUE TITLE
Updates: 2023

### ISSUE THREAD

**Issue by dicook** [dicook/SISBID#19]
- [x] tourr sections, add static outputs animated gif output, linking plots
- [x] interactive plots to ensure that crosstalk is adequately covered
- [x] TB animation - change to a bubble chart
- [x] check software package list, and install instructions 
- [x] check soybean apps still running
- [x] add Susan's name to some sessions

**Comment by dicook** [comment]
If any code changes in the slides, when we update things in these next few days, we will need to update the package list on the README, and in the 0-preamble

**Comment by dicook** [comment]
Apps still running but we don't list them in the slides, should we?

- https://shiny.soybase.org/CNV/
- https://shiny.soybase.org/SNP/

**Comment by srvanderplas** [comment]
I'm honestly shocked they're still running.
